name: Pre-Merge Version Check

on:
  pull_request:
    types: [opened, synchronize, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  pre-merge-version:
    name: Check Next Semantic Version
    runs-on: ubuntu-latest
    if: github.repository == 'stratus-test/stratus-actions'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if last commit was made by the app
        id: skip
        run: |
          # Get the latest commit SHA on the PR branch
          COMMIT_SHA="${{ github.event.pull_request.head.sha }}"
          # Get the author login using the GitHub API
          AUTHOR_LOGIN=$(gh api repos/${{ github.repository }}/commits/$COMMIT_SHA --jq '.author.login')
          echo "Author login: $AUTHOR_LOGIN"
          # Replace 'stratus-ga-bot-stratus-test[bot]' with your app's bot login
          if [[ "$AUTHOR_LOGIN" == "stratus-ga-bot-stratus-test[bot]" ]]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Preview Next Version
        if: steps.skip.outputs.skip != 'true'
        id: version
        uses: ./release
        with:
          dry-run: true
      - name: Comment Next Version on PR
        if: github.event_name == 'pull_request' && steps.skip.outputs.skip != 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const version = process.env.VERSION || '${{ steps.version.outputs.new_version }}';
            const body = `🔢 If merged now, the next release version will be: **${version}**\n\nThe action.yml and pyproject.toml have been updated in this PR branch.`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });
      - name: Update all action.yml, action.yaml, and pyproject.toml files with next version
        id: update-files
        if: steps.skip.outputs.skip != 'true'
        run: |
          VERSION=${{ steps.version.outputs.new_version }}
          VERSION_NO_V=${VERSION#v}
          MAJOR_TAG=v${VERSION_NO_V%%.*}
          # Update all action.yml and action.yaml image tags (handle both : and @ before version)
          find . -type f \( -name action.yml -o -name action.yaml \) | while read f; do
            sed -i -E "s|image: \"docker://ghcr.io/.*/stratus-actions/.+[:@][^\"]*\"|image: \"docker://ghcr.io/${{ github.repository }}/$(basename $(dirname $f)):${VERSION}\"|" "$f"
          done
          # Update all pyproject.toml version fields
          find . -type f -name pyproject.toml | while read f; do
            sed -i "s/^version = \".*\"/version = \"${VERSION_NO_V}\"/" "$f"
          done
          # Update all .md files to reference the latest major tag (e.g., @v1)
          find . -type f -name "*.md" | while read f; do
            sed -i -E "s|(stratus-actions/[a-zA-Z0-9_-]+)@[^\s'\"]+|\1@${MAJOR_TAG}|g" "$f"
          done
          echo "Show updated files:"
          git status --porcelain
          if git status --porcelain | grep .; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Create GitHub App JWT and Installation Access Token
        if: steps.update-files.outputs.changed == 'true' && steps.skip.outputs.skip != 'true'
        id: jwt
        env:
          STRATUS_GA_BOT_PEM: ${{ secrets.STRATUS_GA_BOT_PEM }}
          STRATUS_GA_BOT_ID: ${{ vars.STRATUS_GA_BOT_ID }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
        run: |
          # Install jq and openssl if not present
          sudo apt-get update && sudo apt-get install -y jq

          # Write PEM to file
          echo "$STRATUS_GA_BOT_PEM" > private-key.pem

          # Generate JWT
          now=$(date +%s)
          exp=$((now + 540))
          header='{"alg":"RS256","typ":"JWT"}'
          payload="{\"iat\":$now,\"exp\":$exp,\"iss\":\"$STRATUS_GA_BOT_ID\"}"
          base64url() { openssl base64 -e -A | tr '+/' '-_' | tr -d '='; }
          header_b64=$(echo -n "$header" | base64url)
          payload_b64=$(echo -n "$payload" | base64url)
          unsigned_token="$header_b64.$payload_b64"
          signature=$(echo -n "$unsigned_token" | openssl dgst -sha256 -sign private-key.pem | base64url)
          jwt="$unsigned_token.$signature"

          # Get installation ID
          installation_id=$(curl -s -H "Authorization: Bearer $jwt" -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$GITHUB_REPOSITORY/installation | jq -r .id)

          # Get installation access token
          access_token=$(curl -s -X POST -H "Authorization: Bearer $jwt" -H "Accept: application/vnd.github+json" \
            https://api.github.com/app/installations/$installation_id/access_tokens | jq -r .token)

          echo "strauts_ga_bot_installation_token=$access_token" >> $GITHUB_OUTPUT

          rm private-key.pem
      - name: Commit and push version bump via API
        if: steps.update-files.outputs.changed == 'true' && steps.skip.outputs.skip != 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.jwt.outputs.strauts_ga_bot_installation_token }}
          script: |
            const fs = require('fs');
            const path = require('path');

            // Get current branch info
            const branch = context.payload.pull_request.head.ref;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const version = '${{ steps.version.outputs.new_version }}';

            console.log(`Updating files on branch: ${branch}`);

            try {
              // Get current commit SHA of the branch
              const branchRef = await github.rest.git.getRef({
                owner,
                repo,
                ref: `heads/${branch}`
              });

              const currentCommitSha = branchRef.data.object.sha;

              // Get current tree
              const currentCommit = await github.rest.git.getCommit({
                owner,
                repo,
                commit_sha: currentCommitSha
              });

              // Read updated files
              const actionYmlContent = fs.readFileSync('build-scope-analyzer/action.yml', 'utf8');
              const pyprojectTomlContent = fs.readFileSync('build-scope-analyzer/pyproject.toml', 'utf8');

              // Create blobs for the updated files
              const actionYmlBlob = await github.rest.git.createBlob({
                owner,
                repo,
                content: Buffer.from(actionYmlContent).toString('base64'),
                encoding: 'base64'
              });

              const pyprojectTomlBlob = await github.rest.git.createBlob({
                owner,
                repo,
                content: Buffer.from(pyprojectTomlContent).toString('base64'),
                encoding: 'base64'
              });

              // Create new tree with updated files
              const newTree = await github.rest.git.createTree({
                owner,
                repo,
                base_tree: currentCommit.data.tree.sha,
                tree: [
                  {
                    path: 'build-scope-analyzer/action.yml',
                    mode: '100644',
                    type: 'blob',
                    sha: actionYmlBlob.data.sha
                  },
                  {
                    path: 'build-scope-analyzer/pyproject.toml',
                    mode: '100644',
                    type: 'blob',
                    sha: pyprojectTomlBlob.data.sha
                  }
                ]
              });

              // Create new commit with explicit committer
              const newCommit = await github.rest.git.createCommit({
                owner,
                repo,
                message: `chore: bump version to ${version} [pre-merge]`,
                tree: newTree.data.sha,
                parents: [currentCommitSha],
              });

              // Update branch reference
              await github.rest.git.updateRef({
                owner,
                repo,
                ref: `heads/${branch}`,
                sha: newCommit.data.sha
              });

              console.log(`Successfully updated branch ${branch} with new commit: ${newCommit.data.sha}`);

            } catch (error) {
              console.error('Error updating files via API:', error);
              throw error;
            }

    # Require this job to pass before merging (set branch protection in GitHub UI)
