name: Simple Release

on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Release
        id: release
        uses: ./release
        with:
          draft: false
          prerelease: false

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/build-scope-analyzer
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=sha,format=short
            latest

      - name: Build and push Docker images
        env:
          DOCKER_METADATA_OUTPUT_TAGS: ${{ steps.meta.outputs.tags }}
          DOCKER_METADATA_OUTPUT_LABELS: ${{ steps.meta.outputs.labels }}
        run: |
          ORG_REPO=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')
          IMAGE=ghcr.io/$ORG_REPO/build-scope-analyzer
          # Build with all tags and labels
          docker buildx build \
            --push \
            --platform linux/amd64 \
            --tag $IMAGE:sha-$(git rev-parse --short=7 ${{ github.sha }}) \
            $(echo "$DOCKER_METADATA_OUTPUT_TAGS" | xargs -n 1 echo --tag) \
            $(echo "$DOCKER_METADATA_OUTPUT_LABELS" | xargs -n 1 echo --label) \
            .