name: Simple Release

# This workflow uses the simplified release action from this repository
# The action handles version bumping based on PR labels and creates releases with GitHub's native notes

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Release
        id: release
        uses: ./release # Uses the release action from this repository
        with:
          draft: false
          prerelease: false

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull image by SHA tag
        run: |
          SHORT_SHA=$(git rev-parse --short=8 ${{ github.sha }})
          ORG_REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker pull ghcr.io/$ORG_REPO/build-scope-analyzer:sha-$SHORT_SHA

      - name: Tag and push release images
        run: |
          SEMVER=${{ steps.release.outputs.new_version }}
          SHORT_SHA=$(git rev-parse --short=8 ${{ github.sha }})
          ORG_REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker tag ghcr.io/$ORG_REPO/build-scope-analyzer:sha-$SHORT_SHA ghcr.io/$ORG_REPO/build-scope-analyzer:latest
          docker tag ghcr.io/$ORG_REPO/build-scope-analyzer:sha-$SHORT_SHA ghcr.io/$ORG_REPO/build-scope-analyzer:$SEMVER
          docker push ghcr.io/$ORG_REPO/build-scope-analyzer:latest
          docker push ghcr.io/$ORG_REPO/build-scope-analyzer:$SEMVER
