name: Simple Release

on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  create-release:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' && github.repository == 'stratus-test/stratus-gh-actions' # Only run on the base repository
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.release.outputs.release.new_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Release
        id: release
        uses: ./release
        with:
          draft: false
          prerelease: false

  docker-build:
    needs: create-release
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' && github.repository == 'stratus-test/stratus-gh-actions' # Only run on the base repository
    uses: ./github/workflows/docker-build.yml
    with:
      ref: ${{ needs.create-release.outputs.new_version }}